version: '3'
services:
  hustle-mysqldb:
    container_name: hustle-mysqldb
    image: mysql:latest
    hostname: "dcsmysql"
    environment:
      MYSQL_DATABASE: hustle-mysqldb
      MYSQL_HOST: dcsmysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: supersecret
      TZ: Asia/Kolkata
    ports:
      - "3306:3306"

  hustle-postgresdb:
    container_name: hustle-postgresdb
    image: postgres:latest
    hostname: "dcspostgres"
    environment:
      POSTGRES_DATABASE: hustle-postgresdb 
      POSTGRES_HOST: dcspostgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: supersecret
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"

  hustle-rabbitmq:
    container_name: hustle-rabbitmq
    image: rabbitmq:management
    hostname: "rabbitmq"
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "45672:5672"
      - "45673:15672"
      - "45693:15692"

  hustle-redis-master:
    container_name: hustle-redis-master
    image: redis:latest
    hostname: "hustle-redis-master"
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - REDIS_PASSWORD=my_master_password
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis-master/data:/data
    ports:
      - "6379:6379"
  
  hustle-redis-replica:
    container_name: hustle-redis-replica
    image: redis:latest
    hostname: "hustle-redis-replica"
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=hustle-redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_master_password
      - REDIS_PASSWORD=my_replica_password
    depends_on:
      - hustle-redis-master
    ports:
      - "16379:6379"